In [1]:
import numpy as np


1. Create a 5x5 identity matrix, then replace the diagonal with values 10, 20, 30, 40, 50.

In [6]:
a1 = np.eye(5)
np.fill_diagonal(a1, [10,20,30,40,50])
a1

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.],
       [ 0.,  0., 30.,  0.,  0.],
       [ 0.,  0.,  0., 40.,  0.],
       [ 0.,  0.,  0.,  0., 50.]])


2. Given two 2D arrays of different shapes, use broadcasting to compute their outer sum (no loops).

In [9]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
# 2,3
arr2 = np.array([[1],[2]])
# 2,1

arr1 = arr1[:,:,np.newaxis, np.newaxis]
arr2 = arr2[np.newaxis, np.newaxis, :,:]

result = arr1 + arr2
print(result)
print(result.shape)

[[[[2]
   [3]]

  [[3]
   [4]]

  [[4]
   [5]]]


 [[[5]
   [6]]

  [[6]
   [7]]

  [[7]
   [8]]]]
(2, 3, 2, 1)


3. Create an array of 100 random numbers from a normal distribution and clip all values outside 2 standard deviations.

In [17]:
normal_arr = np.random.randn(100)

std_arr = np.std(normal_arr)

result = np.clip(normal_arr, -2*std_arr, 2*std_arr)

print(result)
print("Min:", result.min(), "Max:", result.max())

[-0.81425882 -0.39997717 -0.55830017  0.88769902  0.67761338 -0.05306275
 -1.27657366 -0.41527544  1.70916848  1.28922407  0.45389456 -0.01264404
 -0.22653103 -1.61424116 -0.78721241 -0.06794753  1.66782383  0.49677591
  1.4310236  -1.12254054 -1.22069969 -0.48227985 -0.29534991 -1.10667249
  0.89488525  1.43864759  0.42738723 -0.32725578 -0.47005886  0.98936396
  0.67973646 -1.0560002  -0.39519259  0.69802065  1.28975179  1.33293389
  0.74878692  1.95318623  0.02291666 -1.18559523 -0.11746744  0.49638375
  1.66886267  0.50981624  0.62352975 -0.6097067  -0.9202579  -1.95318623
  1.29066157 -0.21111698 -0.08296518 -0.44725298  1.41093281 -0.58221439
 -0.79647837 -0.07227031 -1.05456549  0.18257423 -1.66203363  0.77281374
 -1.00661303 -0.72074946  0.45140777 -0.06291702  0.93783369 -0.24250627
 -1.0388045  -0.07603757 -1.95318623 -0.15583589  0.18014476 -0.11506715
 -1.55430571  0.35916395  0.01164672  0.89225968 -0.5912798   0.58658999
  0.55446698  0.97170865 -1.16308458 -1.49661587 -0

4. Use np.argsort() to sort a 2D array by its second column.

In [21]:
arr = np.random.rand(2,2)

result = np.argsort(arr[:,1])

arr[result]


array([[0.6273816 , 0.18198608],
       [0.59592473, 0.28428897]])


5. Create a structured NumPy array to store employee records with fields: name (string), age (int), salary (float).

In [22]:
dtype = [
    ('name', 'U10'),
    ('age', 'i4'),
    ('salary', 'f8')
]

data = np.array([
    ('aryan', 22, 99999),
    ('sammy', 25, 55555),
    ('aady', 22, 44444),
])
data

array([['aryan', '22', '99999'],
       ['sammy', '25', '55555'],
       ['aady', '22', '44444']], dtype='<U21')

6. Given a 4x4 matrix, extract the upper triangular portion using a NumPy function.

In [23]:
arr = np.random.rand(4,4)

np.triu(arr)

array([[0.21888072, 0.46452881, 0.3906551 , 0.72306518],
       [0.        , 0.74380591, 0.87293685, 0.82760923],
       [0.        , 0.        , 0.40591634, 0.31582669],
       [0.        , 0.        , 0.        , 0.18740978]])


7. Stack three 1D arrays of length 5 vertically and horizontally, then describe the shape of each result.

In [5]:
arr1 = np.random.rand(5)
arr2 = np.random.rand(5)
arr3 = np.random.rand(5)

hstack_arr = np.hstack((arr1,arr2,arr3))
vstack_arr = np.vstack((arr1,arr2,arr3))
print(hstack_arr)
print(hstack_arr.shape)

print(vstack_arr)
print(vstack_arr.shape)

[0.13310653 0.17296831 0.45063139 0.98099202 0.89940803 0.76137011
 0.72255784 0.30326089 0.33499954 0.61947329 0.61386543 0.12124386
 0.85385967 0.93979314 0.43169869]
(15,)
[[0.13310653 0.17296831 0.45063139 0.98099202 0.89940803]
 [0.76137011 0.72255784 0.30326089 0.33499954 0.61947329]
 [0.61386543 0.12124386 0.85385967 0.93979314 0.43169869]]
(3, 5)



8. Compute the cumulative sum of an array row-wise and column-wise using np.cumsum().

In [ ]:
arr = np.array([[1,2],[3,4]])
print( np.cumsum(arr, axis=1) ) # row-wise
print( np.cumsum(arr, axis=0) ) # column-wise


[[1 3]
 [3 7]]
[[1 2]
 [4 6]]



9. Given a 2D array, find all rows where the row sum exceeds 100.

In [10]:
arr = np.array([[10,50,50],
          [1,2,3],
          [40,40,30]])

# print(np.where(np.sum(arr, axis=1) > 100))
print(arr[np.sum(arr, axis=1) > 100])

[[10 50 50]
 [40 40 30]]



10. Use np.linalg to compute the inverse and determinant of a 3x3 matrix.

In [11]:
arr = np.random.rand(3,3)
print( np.linalg.inv(arr) )
print( np.linalg.det(arr) )

[[-2.05556277 -0.23375257  1.9727969 ]
 [ 3.30319085  2.20181907 -3.20904942]
 [ 1.46480127  0.01182208 -0.23857461]]
-0.22886918651841828
